services:
  db:
    image: postgres:16
    container_name: choir_db
    environment:
      POSTGRES_DB: choirdb
      POSTGRES_USER: choir_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - choir_db_data_final:/var/lib/postgresql/data

volumes:
  choir_db_data_final: